name: Development (Servus) build
on:
  push:
    branches:
      - dev
jobs:
  build:
    uses: KeenMate/gha-shared/.github/workflows/deploy-docker-image.yml@master
    secrets: inherit
    with:
      image-name: svelte-treeview-showcase
      image-tag: dev
      deployment-host: web-03.km8.vm
      deployment-dir: svelte-treeview-showcase-dev
